### ISSUE TITLE
[tasks/fix-wlst-securerandom-*] WLS java cmdline - dev urandom syntax incorrect

### ISSUE THREAD

**Issue by virtuosity250** [sysco-middleware/ansible-role-oracle-soa#5]
should be: -Djava.security.egd=file:/dev/./urandom
  the other syntax is ignored.

Check with:
  watch -n1 cat /proc/sys/kernel/random/entropy_avail

This needs to be > 3000 <= 4096 (the default configured max)

Note: in most cases this is not enough, the above cmd will show 200 (bits) or less. Many virtual machines & containers are still starved of entropy - which can affect services outside of Java, OHS, etc.

Add haveged, or if you have Linux 7u3+ the install can make use of Intel hardware if available, and then /dev/random will then keep up. I've observed a number of cloud vendors (7u3+) don't use the hardware even if available.

**Comment by jeqo** [comment]
Thanks @virtuosity250 for pointing this out! :+1:
